# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-metatdenovo-1.0dev
channels:
  - bioconda
  - defaults
  - conda-forge
  - agbiome
  - r
dependencies:
  - conda-forge::python=3.7.9
  - conda-forge::markdown=3.3.3
  - conda-forge::pymdown-extensions=8.1.1
  - conda-forge::pygments=2.7.4
  - bioconda::fastqc=0.11.9
  - bioconda::multiqc=1.8
  - conda-forge::r-markdown=1.1
  - conda-forge::r-base=3.6.3
  - bioconda::cutadapt=3.2
  - bioconda::trim-galore=0.6.6
  - conda-forge::pigz=2.3.4
  - bioconda::trinity=2.9.1
  - bioconda::transdecoder=5.5.0
  - bioconda::megahit=1.2.9
  - bioconda::diamond=2.0.7
  - bioconda::megan=6.12.3
  - bioconda::prokka=1.14.6
  - bioconda::blast=2.10.1
  - unzip=6.0
  - agbiome::bbtools=37.62
  - bioconda::samtools=1.11
  - bioconda::subread=2.0.1
  - conda-forge::r-optparse=1.6.6
  - conda-forge::r-data.table=1.14.0
  - conda-forge::r-dtplyr=1.1.0
  - conda-forge::r-dplyr=1.0.4
  - r::r-stringr=1.4.0
  - r::r-r.utils=2.8.0
  - r::r-tidyr=0.8.3
  - bioconda::spades=3.14.1
  - bioconda::khmer=3.0.0a3
  - bioconda::kraken2=2.1.1
