# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-metatdenovo-1.0dev
channels:
  - bioconda
  - defaults
  - conda-forge
  - agbiome
dependencies:
  - python=3.7.9
  - markdown=3.3.3
  - pymdown-extensions=8.1.1
  - pygments=2.7.4
  - fastqc=0.11.9
  - multiqc=1.9
  - r-markdown=0.9
  - r-base=3.6.1
  - cutadapt=3.2
  - trim-galore=0.6.6
  - pigz=2.4
  - trinity=2.9.1
  - transdecoder=5.5
  - megahit=1.2.9
  - diamond=2.0.7
  - megan=6.12.3
  - prokka=1.14.6
  - blast=2.10.1
  - unzip=6.0
  - bbtools=37.62
  - samtools=1.11
  - subread=2.0.1
  - r-optparse=1.6.2
  - r-data.table=1.14.0
  - r-dtplyr=1.1.0
  - r-dplyr=1.0.4
  - r-stringr=1.4.0
  - r-r.utils=2.8.0
  - r-tidyr=0.8.3
  - spades=3.14.1
